import type { Fixture } from './fixtureTypes'
import { PARSER_VERSION } from './fixtureTypes'

export const airtimeFixtures: Fixture[] = [
  {
    description: 'airtime, with balance',
    raw: 'AIR1AAAAA1 Confirmed. You bought Ksh100.00 of airtime on 16/7/26 at 6:00 PM. New M-PESA balance is Ksh400.00.',
    expected: {
      amountCents: 10000,
      kind: 'expense',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'AIR1AAAAA1',
      occurredAt: '2026-07-16T15:00:00.000Z',
      newBalanceCents: 40000,
      category: 'Airtime & Data',
      family: 'airtime',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'AIR1AAAAA1 Confirmed. You bought Ksh100.00 of airtime on 16/7/26 at 6:00 PM. New M-PESA balance is Ksh400.00.',
      patternId: 'airtime-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'airtime, no balance line',
    raw: 'AIR1AAAAA2 Confirmed. You bought Ksh50.00 of airtime on 17/7/26 at 2:45 PM.',
    expected: {
      amountCents: 5000,
      kind: 'expense',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'AIR1AAAAA2',
      occurredAt: '2026-07-17T11:45:00.000Z',
      newBalanceCents: null,
      category: 'Airtime & Data',
      family: 'airtime',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'AIR1AAAAA2 Confirmed. You bought Ksh50.00 of airtime on 17/7/26 at 2:45 PM.',
      patternId: 'airtime-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'airtime, larger amount',
    raw: 'AIR1AAAAA3 Confirmed. You bought Ksh500.00 of airtime on 18/7/26 at 3:15 PM. New M-PESA balance is Ksh1,200.00.',
    expected: {
      amountCents: 50000,
      kind: 'expense',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'AIR1AAAAA3',
      occurredAt: '2026-07-18T12:15:00.000Z',
      newBalanceCents: 120000,
      category: 'Airtime & Data',
      family: 'airtime',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'AIR1AAAAA3 Confirmed. You bought Ksh500.00 of airtime on 18/7/26 at 3:15 PM. New M-PESA balance is Ksh1,200.00.',
      patternId: 'airtime-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'airtime, minimum top-up amount',
    raw: 'AIR1AAAAA4 Confirmed. You bought Ksh20.00 of airtime on 19/7/26 at 3:00 PM. New M-PESA balance is Ksh80.00.',
    expected: {
      amountCents: 2000,
      kind: 'expense',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'AIR1AAAAA4',
      occurredAt: '2026-07-19T12:00:00.000Z',
      newBalanceCents: 8000,
      category: 'Airtime & Data',
      family: 'airtime',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'AIR1AAAAA4 Confirmed. You bought Ksh20.00 of airtime on 19/7/26 at 3:00 PM. New M-PESA balance is Ksh80.00.',
      patternId: 'airtime-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'airtime, KES 1,000 top-up',
    raw: 'AIR1AAAAA5 Confirmed. You bought Ksh1,000.00 of airtime on 21/7/26 at 10:00 AM. New M-PESA balance is Ksh3,400.00.',
    expected: {
      amountCents: 100000,
      kind: 'expense',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'AIR1AAAAA5',
      occurredAt: '2026-07-21T07:00:00.000Z',
      newBalanceCents: 340000,
      category: 'Airtime & Data',
      family: 'airtime',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'AIR1AAAAA5 Confirmed. You bought Ksh1,000.00 of airtime on 21/7/26 at 10:00 AM. New M-PESA balance is Ksh3,400.00.',
      patternId: 'airtime-v1',
      parserVersion: PARSER_VERSION,
    },
  },
]
