import type { Fixture } from './fixtureTypes'
import { PARSER_VERSION } from './fixtureTypes'

export const buyGoodsFixtures: Fixture[] = [
  {
    description: 'buy goods, supermarket till, zero fee and balance',
    raw: 'TLL1AAAAA1 Confirmed. Ksh450.00 paid to NAIVAS LTD. on 8/7/26 at 10:00 AM. New M-PESA balance is Ksh1,050.00. Transaction cost, Ksh0.00.',
    expected: {
      amountCents: 45000,
      kind: 'expense',
      feeCents: 0,
      merchant: 'NAIVAS LTD',
      accountReference: null,
      mpesaRef: 'TLL1AAAAA1',
      occurredAt: '2026-07-08T07:00:00.000Z',
      newBalanceCents: 105000,
      category: null,
      family: 'buy_goods',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'TLL1AAAAA1 Confirmed. Ksh450.00 paid to NAIVAS LTD. on 8/7/26 at 10:00 AM. New M-PESA balance is Ksh1,050.00. Transaction cost, Ksh0.00.',
      patternId: 'buy-goods-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'buy goods, cafe, no fee/balance lines',
    raw: 'TLL1AAAAA2 Confirmed. Ksh120.00 paid to JAVA HOUSE WESTLANDS. on 16/7/26 at 6:00 PM.',
    expected: {
      amountCents: 12000,
      kind: 'expense',
      feeCents: 0,
      merchant: 'JAVA HOUSE WESTLANDS',
      accountReference: null,
      mpesaRef: 'TLL1AAAAA2',
      occurredAt: '2026-07-16T15:00:00.000Z',
      newBalanceCents: null,
      category: null,
      family: 'buy_goods',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'TLL1AAAAA2 Confirmed. Ksh120.00 paid to JAVA HOUSE WESTLANDS. on 16/7/26 at 6:00 PM.',
      patternId: 'buy-goods-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'buy goods, hypermarket, balance only',
    raw: 'TLL1AAAAA3 Confirmed. Ksh2,750.00 paid to CARREFOUR KENYA. on 5/7/26 at 2:45 PM. New M-PESA balance is Ksh4,000.00.',
    expected: {
      amountCents: 275000,
      kind: 'expense',
      feeCents: 0,
      merchant: 'CARREFOUR KENYA',
      accountReference: null,
      mpesaRef: 'TLL1AAAAA3',
      occurredAt: '2026-07-05T11:45:00.000Z',
      newBalanceCents: 400000,
      category: null,
      family: 'buy_goods',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'TLL1AAAAA3 Confirmed. Ksh2,750.00 paid to CARREFOUR KENYA. on 5/7/26 at 2:45 PM. New M-PESA balance is Ksh4,000.00.',
      patternId: 'buy-goods-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'buy goods, fuel station, cents amount',
    raw: 'TLL1AAAAA4 Confirmed. Ksh89.50 paid to TOTAL ENERGIES KILIMANI. on 17/7/26 at 2:45 PM. New M-PESA balance is Ksh300.00. Transaction cost, Ksh0.00.',
    expected: {
      amountCents: 8950,
      kind: 'expense',
      feeCents: 0,
      merchant: 'TOTAL ENERGIES KILIMANI',
      accountReference: null,
      mpesaRef: 'TLL1AAAAA4',
      occurredAt: '2026-07-17T11:45:00.000Z',
      newBalanceCents: 30000,
      category: null,
      family: 'buy_goods',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'TLL1AAAAA4 Confirmed. Ksh89.50 paid to TOTAL ENERGIES KILIMANI. on 17/7/26 at 2:45 PM. New M-PESA balance is Ksh300.00. Transaction cost, Ksh0.00.',
      patternId: 'buy-goods-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'buy goods, restaurant, larger amount',
    raw: 'TLL1AAAAA5 Confirmed. Ksh6,000.00 paid to ARTCAFFE. on 18/7/26 at 3:15 PM. New M-PESA balance is Ksh9,500.00.',
    expected: {
      amountCents: 600000,
      kind: 'expense',
      feeCents: 0,
      merchant: 'ARTCAFFE',
      accountReference: null,
      mpesaRef: 'TLL1AAAAA5',
      occurredAt: '2026-07-18T12:15:00.000Z',
      newBalanceCents: 950000,
      category: null,
      family: 'buy_goods',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'TLL1AAAAA5 Confirmed. Ksh6,000.00 paid to ARTCAFFE. on 18/7/26 at 3:15 PM. New M-PESA balance is Ksh9,500.00.',
      patternId: 'buy-goods-v1',
      parserVersion: PARSER_VERSION,
    },
  },
]
