import type { Fixture } from './fixtureTypes'
import { PARSER_VERSION } from './fixtureTypes'

export const depositFixtures: Fixture[] = [
  {
    description: 'deposit, with balance',
    raw: 'DEP1AAAAA1 Confirmed. You have deposited Ksh5,000.00 to your M-PESA account from agent 123456 - JOHN AGENT SHOP on 9/7/26 at 10:15 AM. New M-PESA balance is Ksh5,500.00.',
    expected: {
      amountCents: 500000,
      kind: 'transfer',
      feeCents: 0,
      merchant: '123456 - JOHN AGENT SHOP',
      accountReference: null,
      mpesaRef: 'DEP1AAAAA1',
      occurredAt: '2026-07-09T07:15:00.000Z',
      newBalanceCents: 550000,
      category: null,
      family: 'deposit',
      counterAccountHint: 'cash',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'DEP1AAAAA1 Confirmed. You have deposited Ksh5,000.00 to your M-PESA account from agent 123456 - JOHN AGENT SHOP on 9/7/26 at 10:15 AM. New M-PESA balance is Ksh5,500.00.',
      patternId: 'deposit-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'deposit, no balance line',
    raw: 'DEP1AAAAA2 Confirmed. You have deposited Ksh1,000.00 to your M-PESA account from agent 654321 - CITY AGENT on 14/7/26 at 8:00 AM.',
    expected: {
      amountCents: 100000,
      kind: 'transfer',
      feeCents: 0,
      merchant: '654321 - CITY AGENT',
      accountReference: null,
      mpesaRef: 'DEP1AAAAA2',
      occurredAt: '2026-07-14T05:00:00.000Z',
      newBalanceCents: null,
      category: null,
      family: 'deposit',
      counterAccountHint: 'cash',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'DEP1AAAAA2 Confirmed. You have deposited Ksh1,000.00 to your M-PESA account from agent 654321 - CITY AGENT on 14/7/26 at 8:00 AM.',
      patternId: 'deposit-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'deposit, large amount',
    raw: 'DEP1AAAAA3 Confirmed. You have deposited Ksh20,000.00 to your M-PESA account from agent 998877 - TOWN CENTRE AGENT on 2/7/26 at 10:00 AM. New M-PESA balance is Ksh21,300.00.',
    expected: {
      amountCents: 2000000,
      kind: 'transfer',
      feeCents: 0,
      merchant: '998877 - TOWN CENTRE AGENT',
      accountReference: null,
      mpesaRef: 'DEP1AAAAA3',
      occurredAt: '2026-07-02T07:00:00.000Z',
      newBalanceCents: 2130000,
      category: null,
      family: 'deposit',
      counterAccountHint: 'cash',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'DEP1AAAAA3 Confirmed. You have deposited Ksh20,000.00 to your M-PESA account from agent 998877 - TOWN CENTRE AGENT on 2/7/26 at 10:00 AM. New M-PESA balance is Ksh21,300.00.',
      patternId: 'deposit-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'deposit, small amount',
    raw: 'DEP1AAAAA4 Confirmed. You have deposited Ksh250.00 to your M-PESA account from agent 445566 - ESTATE AGENT SHOP on 8/7/26 at 10:00 AM. New M-PESA balance is Ksh900.00.',
    expected: {
      amountCents: 25000,
      kind: 'transfer',
      feeCents: 0,
      merchant: '445566 - ESTATE AGENT SHOP',
      accountReference: null,
      mpesaRef: 'DEP1AAAAA4',
      occurredAt: '2026-07-08T07:00:00.000Z',
      newBalanceCents: 90000,
      category: null,
      family: 'deposit',
      counterAccountHint: 'cash',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'DEP1AAAAA4 Confirmed. You have deposited Ksh250.00 to your M-PESA account from agent 445566 - ESTATE AGENT SHOP on 8/7/26 at 10:00 AM. New M-PESA balance is Ksh900.00.',
      patternId: 'deposit-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'deposit, market agent',
    raw: 'DEP1AAAAA5 Confirmed. You have deposited Ksh8,500.00 to your M-PESA account from agent 112233 - MARKET AGENT on 6/7/26 at 9:00 AM. New M-PESA balance is Ksh9,000.00.',
    expected: {
      amountCents: 850000,
      kind: 'transfer',
      feeCents: 0,
      merchant: '112233 - MARKET AGENT',
      accountReference: null,
      mpesaRef: 'DEP1AAAAA5',
      occurredAt: '2026-07-06T06:00:00.000Z',
      newBalanceCents: 900000,
      category: null,
      family: 'deposit',
      counterAccountHint: 'cash',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'DEP1AAAAA5 Confirmed. You have deposited Ksh8,500.00 to your M-PESA account from agent 112233 - MARKET AGENT on 6/7/26 at 9:00 AM. New M-PESA balance is Ksh9,000.00.',
      patternId: 'deposit-v1',
      parserVersion: PARSER_VERSION,
    },
  },
]
