import type { Fixture } from './fixtureTypes'
import { PARSER_VERSION } from './fixtureTypes'

/**
 * Fuliza drawdown — never income (borrowed overdraft funds), so
 * `kind: 'transfer'` (money flows INTO M-PESA from the Fuliza facility,
 * `transferDirection: 'counter_to_mpesa'`). The Fuliza access fee, when the
 * message includes it, rides along as `feeCents` for the integrator to
 * split into a "Fees & Fuliza charges" expense row exactly like a
 * withdrawal fee.
 */
export const fulizaDrawdownFixtures: Fixture[] = [
  {
    description: 'Fuliza drawdown, with access fee and balance',
    raw: 'FLZ1AAAAA1 Confirmed. You have used Fuliza M-PESA. Amount used Ksh500.00 on 20/7/26 at 8:20 PM. Access fee charged Ksh10.00. Total Fuliza M-PESA outstanding is Ksh510.00. New M-PESA balance is Ksh0.00.',
    expected: {
      amountCents: 50000,
      kind: 'transfer',
      feeCents: 1000,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLZ1AAAAA1',
      occurredAt: '2026-07-20T17:20:00.000Z',
      newBalanceCents: 0,
      category: null,
      family: 'fuliza_drawdown',
      counterAccountHint: 'bank',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'FLZ1AAAAA1 Confirmed. You have used Fuliza M-PESA. Amount used Ksh500.00 on 20/7/26 at 8:20 PM. Access fee charged Ksh10.00. Total Fuliza M-PESA outstanding is Ksh510.00. New M-PESA balance is Ksh0.00.',
      patternId: 'fuliza-drawdown-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Fuliza drawdown, no access fee line',
    raw: 'FLZ1AAAAA2 Confirmed. You have used Fuliza M-PESA. Amount used Ksh1,200.00 on 22/7/26 at 7:05 AM. New M-PESA balance is Ksh200.00.',
    expected: {
      amountCents: 120000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLZ1AAAAA2',
      occurredAt: '2026-07-22T04:05:00.000Z',
      newBalanceCents: 20000,
      category: null,
      family: 'fuliza_drawdown',
      counterAccountHint: 'bank',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'FLZ1AAAAA2 Confirmed. You have used Fuliza M-PESA. Amount used Ksh1,200.00 on 22/7/26 at 7:05 AM. New M-PESA balance is Ksh200.00.',
      patternId: 'fuliza-drawdown-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Fuliza drawdown, cents amount with fee',
    raw: 'FLZ1AAAAA3 Confirmed. You have used Fuliza M-PESA. Amount used Ksh250.50 on 23/7/26 at 1:40 PM. Access fee charged Ksh5.00. Total Fuliza M-PESA outstanding is Ksh255.50. New M-PESA balance is Ksh50.00.',
    expected: {
      amountCents: 25050,
      kind: 'transfer',
      feeCents: 500,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLZ1AAAAA3',
      occurredAt: '2026-07-23T10:40:00.000Z',
      newBalanceCents: 5000,
      category: null,
      family: 'fuliza_drawdown',
      counterAccountHint: 'bank',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'FLZ1AAAAA3 Confirmed. You have used Fuliza M-PESA. Amount used Ksh250.50 on 23/7/26 at 1:40 PM. Access fee charged Ksh5.00. Total Fuliza M-PESA outstanding is Ksh255.50. New M-PESA balance is Ksh50.00.',
      patternId: 'fuliza-drawdown-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Fuliza drawdown, no balance line',
    raw: 'FLZ1AAAAA4 Confirmed. You have used Fuliza M-PESA. Amount used Ksh3,000.00 on 24/7/26 at 11:15 AM. Access fee charged Ksh35.00. Total Fuliza M-PESA outstanding is Ksh3,035.00.',
    expected: {
      amountCents: 300000,
      kind: 'transfer',
      feeCents: 3500,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLZ1AAAAA4',
      occurredAt: '2026-07-24T08:15:00.000Z',
      newBalanceCents: null,
      category: null,
      family: 'fuliza_drawdown',
      counterAccountHint: 'bank',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'FLZ1AAAAA4 Confirmed. You have used Fuliza M-PESA. Amount used Ksh3,000.00 on 24/7/26 at 11:15 AM. Access fee charged Ksh35.00. Total Fuliza M-PESA outstanding is Ksh3,035.00.',
      patternId: 'fuliza-drawdown-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Fuliza drawdown, small amount, all optional fields present',
    raw: 'FLZ1AAAAA5 Confirmed. You have used Fuliza M-PESA. Amount used Ksh100.00 on 25/7/26 at 4:50 PM. Access fee charged Ksh2.00. Total Fuliza M-PESA outstanding is Ksh102.00. New M-PESA balance is Ksh0.00.',
    expected: {
      amountCents: 10000,
      kind: 'transfer',
      feeCents: 200,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLZ1AAAAA5',
      occurredAt: '2026-07-25T13:50:00.000Z',
      newBalanceCents: 0,
      category: null,
      family: 'fuliza_drawdown',
      counterAccountHint: 'bank',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'FLZ1AAAAA5 Confirmed. You have used Fuliza M-PESA. Amount used Ksh100.00 on 25/7/26 at 4:50 PM. Access fee charged Ksh2.00. Total Fuliza M-PESA outstanding is Ksh102.00. New M-PESA balance is Ksh0.00.',
      patternId: 'fuliza-drawdown-v1',
      parserVersion: PARSER_VERSION,
    },
  },
]
