import type { Fixture } from './fixtureTypes'
import { PARSER_VERSION } from './fixtureTypes'

export const fulizaRepaymentFixtures: Fixture[] = [
  {
    description: 'Fuliza repayment, fully paid, with balance',
    raw: 'FLR1AAAAA1 Confirmed. Ksh300.00 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 26/7/26 at 9:30 AM. New Fuliza M-PESA outstanding amount is Ksh0.00. New M-PESA balance is Ksh200.00.',
    expected: {
      amountCents: 30000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLR1AAAAA1',
      occurredAt: '2026-07-26T06:30:00.000Z',
      newBalanceCents: 20000,
      category: null,
      family: 'fuliza_repayment',
      counterAccountHint: 'bank',
      transferDirection: 'mpesa_to_counter',
      reversalOfRef: null,
      rawText: 'FLR1AAAAA1 Confirmed. Ksh300.00 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 26/7/26 at 9:30 AM. New Fuliza M-PESA outstanding amount is Ksh0.00. New M-PESA balance is Ksh200.00.',
      patternId: 'fuliza-repayment-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Fuliza repayment, no outstanding-amount line',
    raw: 'FLR1AAAAA2 Confirmed. Ksh1,000.00 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 27/7/26 at 10:00 AM. New M-PESA balance is Ksh500.00.',
    expected: {
      amountCents: 100000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLR1AAAAA2',
      occurredAt: '2026-07-27T07:00:00.000Z',
      newBalanceCents: 50000,
      category: null,
      family: 'fuliza_repayment',
      counterAccountHint: 'bank',
      transferDirection: 'mpesa_to_counter',
      reversalOfRef: null,
      rawText: 'FLR1AAAAA2 Confirmed. Ksh1,000.00 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 27/7/26 at 10:00 AM. New M-PESA balance is Ksh500.00.',
      patternId: 'fuliza-repayment-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Fuliza repayment, no balance line, cents amount',
    raw: 'FLR1AAAAA3 Confirmed. Ksh75.25 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 28/7/26 at 12:00 PM. New Fuliza M-PESA outstanding amount is Ksh0.00.',
    expected: {
      amountCents: 7525,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLR1AAAAA3',
      occurredAt: '2026-07-28T09:00:00.000Z',
      newBalanceCents: null,
      category: null,
      family: 'fuliza_repayment',
      counterAccountHint: 'bank',
      transferDirection: 'mpesa_to_counter',
      reversalOfRef: null,
      rawText: 'FLR1AAAAA3 Confirmed. Ksh75.25 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 28/7/26 at 12:00 PM. New Fuliza M-PESA outstanding amount is Ksh0.00.',
      patternId: 'fuliza-repayment-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Fuliza repayment, large amount',
    raw: 'FLR1AAAAA4 Confirmed. Ksh5,500.00 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 29/6/26 at 3:00 PM. New M-PESA balance is Ksh1,200.00.',
    expected: {
      amountCents: 550000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLR1AAAAA4',
      occurredAt: '2026-06-29T12:00:00.000Z',
      newBalanceCents: 120000,
      category: null,
      family: 'fuliza_repayment',
      counterAccountHint: 'bank',
      transferDirection: 'mpesa_to_counter',
      reversalOfRef: null,
      rawText: 'FLR1AAAAA4 Confirmed. Ksh5,500.00 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 29/6/26 at 3:00 PM. New M-PESA balance is Ksh1,200.00.',
      patternId: 'fuliza-repayment-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Fuliza repayment, small amount, all optional fields present',
    raw: 'FLR1AAAAA5 Confirmed. Ksh40.00 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 30/6/26 at 8:00 AM. New Fuliza M-PESA outstanding amount is Ksh0.00. New M-PESA balance is Ksh10.00.',
    expected: {
      amountCents: 4000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'FLR1AAAAA5',
      occurredAt: '2026-06-30T05:00:00.000Z',
      newBalanceCents: 1000,
      category: null,
      family: 'fuliza_repayment',
      counterAccountHint: 'bank',
      transferDirection: 'mpesa_to_counter',
      reversalOfRef: null,
      rawText: 'FLR1AAAAA5 Confirmed. Ksh40.00 from your M-PESA has been used to pay your outstanding Fuliza M-PESA on 30/6/26 at 8:00 AM. New Fuliza M-PESA outstanding amount is Ksh0.00. New M-PESA balance is Ksh10.00.',
      patternId: 'fuliza-repayment-v1',
      parserVersion: PARSER_VERSION,
    },
  },
]
