import type { Fixture } from './fixtureTypes'
import { PARSER_VERSION } from './fixtureTypes'

export const mshwariKcbTransferFixtures: Fixture[] = [
  {
    description: 'M-Shwari, to M-Shwari, with balance',
    raw: 'MSW1AAAAA1 Confirmed. Ksh1,000.00 transferred to M-Shwari account on 1/7/26 at 10:00 AM. New M-PESA balance is Ksh200.00.',
    expected: {
      amountCents: 100000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'MSW1AAAAA1',
      occurredAt: '2026-07-01T07:00:00.000Z',
      newBalanceCents: 20000,
      category: null,
      family: 'mshwari_kcb_transfer',
      counterAccountHint: 'bank',
      transferDirection: 'mpesa_to_counter',
      reversalOfRef: null,
      rawText: 'MSW1AAAAA1 Confirmed. Ksh1,000.00 transferred to M-Shwari account on 1/7/26 at 10:00 AM. New M-PESA balance is Ksh200.00.',
      patternId: 'mshwari-out-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'M-Shwari, to M-Shwari, no balance line',
    raw: 'MSW1AAAAA2 Confirmed. Ksh500.00 transferred to M-Shwari account on 2/6/26 at 9:00 AM.',
    expected: {
      amountCents: 50000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'MSW1AAAAA2',
      occurredAt: '2026-06-02T06:00:00.000Z',
      newBalanceCents: null,
      category: null,
      family: 'mshwari_kcb_transfer',
      counterAccountHint: 'bank',
      transferDirection: 'mpesa_to_counter',
      reversalOfRef: null,
      rawText: 'MSW1AAAAA2 Confirmed. Ksh500.00 transferred to M-Shwari account on 2/6/26 at 9:00 AM.',
      patternId: 'mshwari-out-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'M-Shwari, from M-Shwari, with balance',
    raw: 'MSW1AAAAA3 Confirmed. Ksh1,000.00 transferred from M-Shwari account to your M-PESA account on 3/6/26 at 11:00 AM. New M-PESA balance is Ksh1,200.00.',
    expected: {
      amountCents: 100000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'MSW1AAAAA3',
      occurredAt: '2026-06-03T08:00:00.000Z',
      newBalanceCents: 120000,
      category: null,
      family: 'mshwari_kcb_transfer',
      counterAccountHint: 'bank',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'MSW1AAAAA3 Confirmed. Ksh1,000.00 transferred from M-Shwari account to your M-PESA account on 3/6/26 at 11:00 AM. New M-PESA balance is Ksh1,200.00.',
      patternId: 'mshwari-in-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'M-Shwari, from M-Shwari, no balance line',
    raw: 'MSW1AAAAA4 Confirmed. Ksh2,500.00 transferred from M-Shwari account to your M-PESA account on 6/6/26 at 7:45 AM.',
    expected: {
      amountCents: 250000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'MSW1AAAAA4',
      occurredAt: '2026-06-06T04:45:00.000Z',
      newBalanceCents: null,
      category: null,
      family: 'mshwari_kcb_transfer',
      counterAccountHint: 'bank',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'MSW1AAAAA4 Confirmed. Ksh2,500.00 transferred from M-Shwari account to your M-PESA account on 6/6/26 at 7:45 AM.',
      patternId: 'mshwari-in-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'KCB M-PESA, to KCB, with balance',
    raw: 'KCB1AAAAA1 Confirmed. Ksh3,000.00 transferred to KCB M-PESA account on 4/6/26 at 2:00 PM. New M-PESA balance is Ksh500.00.',
    expected: {
      amountCents: 300000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'KCB1AAAAA1',
      occurredAt: '2026-06-04T11:00:00.000Z',
      newBalanceCents: 50000,
      category: null,
      family: 'mshwari_kcb_transfer',
      counterAccountHint: 'bank',
      transferDirection: 'mpesa_to_counter',
      reversalOfRef: null,
      rawText: 'KCB1AAAAA1 Confirmed. Ksh3,000.00 transferred to KCB M-PESA account on 4/6/26 at 2:00 PM. New M-PESA balance is Ksh500.00.',
      patternId: 'kcb-out-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'KCB M-PESA, from KCB, with balance',
    raw: 'KCB1AAAAA2 Confirmed. Ksh4,000.00 transferred from KCB M-PESA account to your M-PESA account on 5/6/26 at 3:00 PM. New M-PESA balance is Ksh4,500.00.',
    expected: {
      amountCents: 400000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'KCB1AAAAA2',
      occurredAt: '2026-06-05T12:00:00.000Z',
      newBalanceCents: 450000,
      category: null,
      family: 'mshwari_kcb_transfer',
      counterAccountHint: 'bank',
      transferDirection: 'counter_to_mpesa',
      reversalOfRef: null,
      rawText: 'KCB1AAAAA2 Confirmed. Ksh4,000.00 transferred from KCB M-PESA account to your M-PESA account on 5/6/26 at 3:00 PM. New M-PESA balance is Ksh4,500.00.',
      patternId: 'kcb-in-v1',
      parserVersion: PARSER_VERSION,
    },
  },
]
