import type { Fixture } from './fixtureTypes'
import { PARSER_VERSION } from './fixtureTypes'

export const pochiLaBiasharaFixtures: Fixture[] = [
  {
    description: 'Pochi la Biashara, cafe, zero fee and balance',
    raw: 'PCH1AAAAA1 Confirmed. Ksh300.00 sent to JAVA HOUSE - POCHI LA BIASHARA 0711223344 on 19/7/26 at 3:00 PM. New M-PESA balance is Ksh700.00. Transaction cost, Ksh0.00.',
    expected: {
      amountCents: 30000,
      kind: 'expense',
      feeCents: 0,
      merchant: 'JAVA HOUSE - POCHI LA BIASHARA',
      accountReference: null,
      mpesaRef: 'PCH1AAAAA1',
      occurredAt: '2026-07-19T12:00:00.000Z',
      newBalanceCents: 70000,
      category: null,
      family: 'pochi_la_biashara',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'PCH1AAAAA1 Confirmed. Ksh300.00 sent to JAVA HOUSE - POCHI LA BIASHARA 0711223344 on 19/7/26 at 3:00 PM. New M-PESA balance is Ksh700.00. Transaction cost, Ksh0.00.',
      patternId: 'pochi-la-biashara-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Pochi la Biashara, small vendor stall, balance only',
    raw: 'PCH1AAAAA2 Confirmed. Ksh1,500.00 sent to MAMA MBOGA STALL - POCHI LA BIASHARA 0722556677 on 21/7/26 at 10:00 AM. New M-PESA balance is Ksh3,200.00.',
    expected: {
      amountCents: 150000,
      kind: 'expense',
      feeCents: 0,
      merchant: 'MAMA MBOGA STALL - POCHI LA BIASHARA',
      accountReference: null,
      mpesaRef: 'PCH1AAAAA2',
      occurredAt: '2026-07-21T07:00:00.000Z',
      newBalanceCents: 320000,
      category: null,
      family: 'pochi_la_biashara',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'PCH1AAAAA2 Confirmed. Ksh1,500.00 sent to MAMA MBOGA STALL - POCHI LA BIASHARA 0722556677 on 21/7/26 at 10:00 AM. New M-PESA balance is Ksh3,200.00.',
      patternId: 'pochi-la-biashara-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Pochi la Biashara, no fee/balance lines',
    raw: 'PCH1AAAAA3 Confirmed. Ksh650.00 sent to KIOSK CORNER - POCHI LA BIASHARA 0700889900 on 6/7/26 at 9:00 AM.',
    expected: {
      amountCents: 65000,
      kind: 'expense',
      feeCents: 0,
      merchant: 'KIOSK CORNER - POCHI LA BIASHARA',
      accountReference: null,
      mpesaRef: 'PCH1AAAAA3',
      occurredAt: '2026-07-06T06:00:00.000Z',
      newBalanceCents: null,
      category: null,
      family: 'pochi_la_biashara',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'PCH1AAAAA3 Confirmed. Ksh650.00 sent to KIOSK CORNER - POCHI LA BIASHARA 0700889900 on 6/7/26 at 9:00 AM.',
      patternId: 'pochi-la-biashara-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Pochi la Biashara, barber shop, zero fee with balance',
    raw: 'PCH1AAAAA4 Confirmed. Ksh4,200.00 sent to BARBER SHOP - POCHI LA BIASHARA 0733221100 on 8/7/26 at 10:00 AM. New M-PESA balance is Ksh5,000.00. Transaction cost, Ksh0.00.',
    expected: {
      amountCents: 420000,
      kind: 'expense',
      feeCents: 0,
      merchant: 'BARBER SHOP - POCHI LA BIASHARA',
      accountReference: null,
      mpesaRef: 'PCH1AAAAA4',
      occurredAt: '2026-07-08T07:00:00.000Z',
      newBalanceCents: 500000,
      category: null,
      family: 'pochi_la_biashara',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'PCH1AAAAA4 Confirmed. Ksh4,200.00 sent to BARBER SHOP - POCHI LA BIASHARA 0733221100 on 8/7/26 at 10:00 AM. New M-PESA balance is Ksh5,000.00. Transaction cost, Ksh0.00.',
      patternId: 'pochi-la-biashara-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'Pochi la Biashara, salon, small amount',
    raw: 'PCH1AAAAA5 Confirmed. Ksh180.00 sent to SALON PLACE - POCHI LA BIASHARA 0711998877 on 2/7/26 at 10:00 AM. New M-PESA balance is Ksh900.00.',
    expected: {
      amountCents: 18000,
      kind: 'expense',
      feeCents: 0,
      merchant: 'SALON PLACE - POCHI LA BIASHARA',
      accountReference: null,
      mpesaRef: 'PCH1AAAAA5',
      occurredAt: '2026-07-02T07:00:00.000Z',
      newBalanceCents: 90000,
      category: null,
      family: 'pochi_la_biashara',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: null,
      rawText: 'PCH1AAAAA5 Confirmed. Ksh180.00 sent to SALON PLACE - POCHI LA BIASHARA 0711998877 on 2/7/26 at 10:00 AM. New M-PESA balance is Ksh900.00.',
      patternId: 'pochi-la-biashara-v1',
      parserVersion: PARSER_VERSION,
    },
  },
]
