import type { Fixture } from './fixtureTypes'
import { PARSER_VERSION } from './fixtureTypes'

/**
 * Reversal — "the number never lies" (PRD §4.5/§10). `kind: 'transfer'` here
 * is only a safety marker; the real signal is `reversalOfRef`, which the
 * integrator uses to negate the ORIGINAL transaction by `mpesa_ref`. See the
 * big doc comment in `../types.ts`, family 10.
 */
export const reversalFixtures: Fixture[] = [
  {
    description: 'reversal, with balance',
    raw: 'REV1AAAAA1 Confirmed. The reversal of Ksh500.00 for transaction QGH7XXXXX1 on 7/6/26 at 1:10 PM is complete. New M-PESA balance is Ksh1,500.00.',
    expected: {
      amountCents: 50000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'REV1AAAAA1',
      occurredAt: '2026-06-07T10:10:00.000Z',
      newBalanceCents: 150000,
      category: null,
      family: 'reversal',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: 'QGH7XXXXX1',
      rawText: 'REV1AAAAA1 Confirmed. The reversal of Ksh500.00 for transaction QGH7XXXXX1 on 7/6/26 at 1:10 PM is complete. New M-PESA balance is Ksh1,500.00.',
      patternId: 'reversal-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'reversal, no balance line',
    raw: 'REV1AAAAA2 Confirmed. The reversal of Ksh1,200.00 for transaction SNT1AAAAA2 on 8/6/26 at 6:30 PM is complete.',
    expected: {
      amountCents: 120000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'REV1AAAAA2',
      occurredAt: '2026-06-08T15:30:00.000Z',
      newBalanceCents: null,
      category: null,
      family: 'reversal',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: 'SNT1AAAAA2',
      rawText: 'REV1AAAAA2 Confirmed. The reversal of Ksh1,200.00 for transaction SNT1AAAAA2 on 8/6/26 at 6:30 PM is complete.',
      patternId: 'reversal-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'reversal, cents amount',
    raw: 'REV1AAAAA3 Confirmed. The reversal of Ksh250.75 for transaction PBL1AAAAA1 on 9/6/26 at 9:55 AM is complete. New M-PESA balance is Ksh900.00.',
    expected: {
      amountCents: 25075,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'REV1AAAAA3',
      occurredAt: '2026-06-09T06:55:00.000Z',
      newBalanceCents: 90000,
      category: null,
      family: 'reversal',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: 'PBL1AAAAA1',
      rawText: 'REV1AAAAA3 Confirmed. The reversal of Ksh250.75 for transaction PBL1AAAAA1 on 9/6/26 at 9:55 AM is complete. New M-PESA balance is Ksh900.00.',
      patternId: 'reversal-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'reversal, of a withdrawal, large amount',
    raw: 'REV1AAAAA4 Confirmed. The reversal of Ksh10,000.00 for transaction WDL1AAAAA3 on 10/6/26 at 10:05 PM is complete. New M-PESA balance is Ksh12,000.00.',
    expected: {
      amountCents: 1000000,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'REV1AAAAA4',
      occurredAt: '2026-06-10T19:05:00.000Z',
      newBalanceCents: 1200000,
      category: null,
      family: 'reversal',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: 'WDL1AAAAA3',
      rawText: 'REV1AAAAA4 Confirmed. The reversal of Ksh10,000.00 for transaction WDL1AAAAA3 on 10/6/26 at 10:05 PM is complete. New M-PESA balance is Ksh12,000.00.',
      patternId: 'reversal-v1',
      parserVersion: PARSER_VERSION,
    },
  },
  {
    description: 'reversal, of a buy-goods payment, small amount',
    raw: 'REV1AAAAA5 Confirmed. The reversal of Ksh75.00 for transaction TLL1AAAAA2 on 11/6/26 at 4:15 AM is complete. New M-PESA balance is Ksh300.00.',
    expected: {
      amountCents: 7500,
      kind: 'transfer',
      feeCents: 0,
      merchant: null,
      accountReference: null,
      mpesaRef: 'REV1AAAAA5',
      occurredAt: '2026-06-11T01:15:00.000Z',
      newBalanceCents: 30000,
      category: null,
      family: 'reversal',
      counterAccountHint: null,
      transferDirection: null,
      reversalOfRef: 'TLL1AAAAA2',
      rawText: 'REV1AAAAA5 Confirmed. The reversal of Ksh75.00 for transaction TLL1AAAAA2 on 11/6/26 at 4:15 AM is complete. New M-PESA balance is Ksh300.00.',
      patternId: 'reversal-v1',
      parserVersion: PARSER_VERSION,
    },
  },
]
